// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace reactwithnet
{
    public partial class MLModel
    {
        /// <summary>
        /// model input class for MLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Disease")]
            public string Disease { get; set; }

            [ColumnName(@"Symptom_1")]
            public string Symptom_1 { get; set; }

            [ColumnName(@"Symptom_2")]
            public string Symptom_2 { get; set; }

            [ColumnName(@"Symptom_3")]
            public string Symptom_3 { get; set; }

            [ColumnName(@"Symptom_4")]
            public string Symptom_4 { get; set; }

            [ColumnName(@"Symptom_5")]
            public string Symptom_5 { get; set; }

            [ColumnName(@"Symptom_6")]
            public string Symptom_6 { get; set; }

            [ColumnName(@"Symptom_7")]
            public string Symptom_7 { get; set; }

            [ColumnName(@"Symptom_8")]
            public string Symptom_8 { get; set; }

            [ColumnName(@"Symptom_9")]
            public string Symptom_9 { get; set; }

            [ColumnName(@"Symptom_10")]
            public string Symptom_10 { get; set; }

            [ColumnName(@"Symptom_11")]
            public string Symptom_11 { get; set; }

            [ColumnName(@"Symptom_12")]
            public string Symptom_12 { get; set; }

            [ColumnName(@"Symptom_13")]
            public string Symptom_13 { get; set; }

            [ColumnName(@"Symptom_14")]
            public string Symptom_14 { get; set; }

            [ColumnName(@"Symptom_15")]
            public string Symptom_15 { get; set; }

            [ColumnName(@"Symptom_16")]
            public string Symptom_16 { get; set; }

            [ColumnName(@"Symptom_17")]
            public string Symptom_17 { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Disease")]
            public uint Disease { get; set; }

            [ColumnName(@"Symptom_1")]
            public float[] Symptom_1 { get; set; }

            [ColumnName(@"Symptom_2")]
            public float[] Symptom_2 { get; set; }

            [ColumnName(@"Symptom_3")]
            public float[] Symptom_3 { get; set; }

            [ColumnName(@"Symptom_4")]
            public float[] Symptom_4 { get; set; }

            [ColumnName(@"Symptom_5")]
            public float[] Symptom_5 { get; set; }

            [ColumnName(@"Symptom_6")]
            public float[] Symptom_6 { get; set; }

            [ColumnName(@"Symptom_7")]
            public float[] Symptom_7 { get; set; }

            [ColumnName(@"Symptom_8")]
            public float[] Symptom_8 { get; set; }

            [ColumnName(@"Symptom_9")]
            public float[] Symptom_9 { get; set; }

            [ColumnName(@"Symptom_10")]
            public float[] Symptom_10 { get; set; }

            [ColumnName(@"Symptom_11")]
            public float[] Symptom_11 { get; set; }

            [ColumnName(@"Symptom_12")]
            public float[] Symptom_12 { get; set; }

            [ColumnName(@"Symptom_13")]
            public float[] Symptom_13 { get; set; }

            [ColumnName(@"Symptom_14")]
            public float[] Symptom_14 { get; set; }

            [ColumnName(@"Symptom_15")]
            public float[] Symptom_15 { get; set; }

            [ColumnName(@"Symptom_16")]
            public float[] Symptom_16 { get; set; }

            [ColumnName(@"Symptom_17")]
            public float[] Symptom_17 { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
